# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "__pypackages__",
    "build",
    "dist",
    "data",
    "migrations/versions"
]

# Same as Black.
line-length = 100

# Assume Python 3.12
target-version = "py312"

[lint]
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "I", # isort
    "C", # flake8-comprehensions
    "B", # flake8-bugbear
    "PLC0415", # import outside toplevel
]
ignore = [
    "B008", # do not perform function calls in argument defaults
    "C901", # complexity
    "E501", # line too long
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "I"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Unlike Flake8, default to a complexity level of 10.
mccabe.max-complexity = 10

[lint.isort]
known-third-party = ["fastapi", "pydantic", "starlette"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
