"""add memory name

Revision ID: f8c1fc9be252
Revises: b942da1196f0
Create Date: 2026-04-06 12:45:26.136961

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8c1fc9be252"
down_revision: Union[str, Sequence[str], None] = "c1d2e3f4a5b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("memories", sa.Column("name", sa.Text(), nullable=True))
    op.create_index(op.f("ix_memories_name"), "memories", ["name"], unique=False)
    op.create_unique_constraint(
        "uq_memories_name_workspace", "memories", ["name", "workspace_id"]
    )
    # ### end Alembic commands ###

    # Back-fill name from content: if content starts with a short phrase followed
    # by ":", use that phrase as the name.  Skip if the candidate name would
    # collide with another memory in the same workspace.
    op.execute(sa.text("""
        UPDATE memories
        SET
            name    = TRIM(SPLIT_PART(content, ':', 1)),
            content = TRIM(SUBSTRING(content FROM POSITION(':' IN content) + 1))
        WHERE
            POSITION(':' IN content) > 0
            AND CHAR_LENGTH(TRIM(SPLIT_PART(content, ':', 1))) BETWEEN 3 AND 60
            AND name IS NULL
            AND NOT EXISTS (
                SELECT 1 FROM memories m2
                WHERE m2.workspace_id = memories.workspace_id
                  AND m2.id != memories.id
                  AND POSITION(':' IN m2.content) > 0
                  AND CHAR_LENGTH(TRIM(SPLIT_PART(m2.content, ':', 1))) BETWEEN 3 AND 60
                  AND TRIM(SPLIT_PART(m2.content, ':', 1)) = TRIM(SPLIT_PART(memories.content, ':', 1))
            )
    """))


def downgrade() -> None:
    """Downgrade schema."""
    # Restore content: prepend name back if name was set by the back-fill.
    # We can't know which rows were touched, so we restore all rows that have
    # a name — concatenating "name: content".
    op.execute(sa.text("""
        UPDATE memories
        SET content = name || ': ' || content
        WHERE name IS NOT NULL
    """))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_memories_name_workspace", "memories", type_="unique")
    op.drop_index(op.f("ix_memories_name"), table_name="memories")
    op.drop_column("memories", "name")
    # ### end Alembic commands ###
