"""email

Revision ID: b942da1196f0
Revises: a1b2c3d4e5f6
Create Date: 2026-03-22 23:00:16.793828

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b942da1196f0"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_tokens",
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum("verify", "reset", name="tokenpurpose", native_enum=False),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_email_tokens")),
    )
    op.create_index(
        op.f("ix_email_tokens_expires_at"), "email_tokens", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_email_tokens_user_purpose",
        "email_tokens",
        ["user_id", "purpose"],
        unique=False,
    )
    op.add_column(
        "users",
        sa.Column(
            "email_verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###,


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_verified")
    op.drop_index("ix_email_tokens_user_purpose", table_name="email_tokens")
    op.drop_index(op.f("ix_email_tokens_expires_at"), table_name="email_tokens")
    op.drop_table("email_tokens")
    # ### end Alembic commands ###
