"""add memory name

Revision ID: f8c1fc9be252
Revises: b942da1196f0
Create Date: 2026-04-06 12:45:26.136961

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8c1fc9be252"
down_revision: Union[str, Sequence[str], None] = "c1d2e3f4a5b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("memories", sa.Column("name", sa.Text(), nullable=True))
    op.create_index(op.f("ix_memories_name"), "memories", ["name"], unique=False)
    op.create_unique_constraint(
        "uq_memories_name_workspace", "memories", ["name", "workspace_id"]
    )
    # ### end Alembic commands ###

    # Pass 1: extract name from "name: content" pattern where unambiguous.
    op.execute(sa.text("""
        UPDATE memories
        SET
            name    = TRIM(SPLIT_PART(content, ':', 1)),
            content = TRIM(SUBSTRING(content FROM POSITION(':' IN content) + 1))
        WHERE
            POSITION(':' IN content) > 0
            AND CHAR_LENGTH(TRIM(SPLIT_PART(content, ':', 1))) BETWEEN 3 AND 60
            AND name IS NULL
            AND NOT EXISTS (
                SELECT 1 FROM memories m2
                WHERE m2.workspace_id = memories.workspace_id
                  AND m2.id != memories.id
                  AND POSITION(':' IN m2.content) > 0
                  AND CHAR_LENGTH(TRIM(SPLIT_PART(m2.content, ':', 1))) BETWEEN 3 AND 60
                  AND TRIM(SPLIT_PART(m2.content, ':', 1)) = TRIM(SPLIT_PART(memories.content, ':', 1))
            )
    """))

    # Pass 2: fill remaining NULLs from the first 60 chars of content.
    # Append " #<id>" when that prefix would collide with an existing name or
    # another NULL row that generates the same prefix in the same workspace.
    op.execute(sa.text("""
        UPDATE memories m
        SET name = CASE
            WHEN EXISTS (
                SELECT 1 FROM memories m2
                WHERE m2.workspace_id = m.workspace_id
                  AND m2.id != m.id
                  AND (
                      m2.name = LEFT(TRIM(m.content), 60)
                      OR (m2.name IS NULL
                          AND LEFT(TRIM(m2.content), 60) = LEFT(TRIM(m.content), 60))
                  )
            )
            THEN LEFT(TRIM(m.content), 54) || ' #' || m.id::text
            ELSE LEFT(TRIM(m.content), 60)
        END
        WHERE m.name IS NULL
    """))

    op.alter_column("memories", "name", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # Prepend name back into content for all rows (can't distinguish auto-generated
    # names from extracted ones, so we restore everything).
    op.execute(sa.text("""
        UPDATE memories
        SET content = name || ': ' || content
    """))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_memories_name_workspace", "memories", type_="unique")
    op.drop_index(op.f("ix_memories_name"), table_name="memories")
    op.drop_column("memories", "name")
    # ### end Alembic commands ###
